### ISSUE TITLE
Add frame for duplicate companies in work experience

### ISSUE THREAD

**Issue by kurnakovv** [kurnakovv/Resume#21]
Example: company1, company2

```
+----------------------+
| company1: details    |
| company1: details    |
+----------------------+
company2: details
```

We should think about good frame

P.S. Updated, frame is not good idea. Let's merge duplicate companies without frame. Different companies must separate with space like this:

![image](https://github.com/kurnakovv/Resume/assets/59327306/04cac613-9608-499c-9a35-92ad8fd47ecf)

**Comment by TanianaKur** [comment]
Duplicate companies should be placed below the first company or on the same line

**Comment by kurnakovv** [comment]
@TanianaKur all companies must be placed below.
![image](https://github.com/kurnakovv/Resume/assets/59327306/38154412-7319-4ab6-8b1d-aeb5e8b18ea4)

**Comment by TanianaKur** [comment]
@Kurnakovv What is a duplicate companies?

**Comment by kurnakovv** [comment]
@TanianaKur Duplicate companies is companies when I worked (or work) in one company, but in difference teams, for example:
```
company1, team1
company1, team2

company2, team1

company3, team1

company4, team1
company4, team2
```
`company1` and `company4` is duplicate, and they need a frame. But `company2`, `company3` is not duplicate (they don't need a frame)

**Comment by TanianaKur** [comment]
Do you have any suggestions regarding the color and thickness of the frame?

**Comment by kurnakovv** [comment]
@TanianaKur Well, I haven't any good ideas :(
Can you please think about it? The main requirements is:
1) Common color (violet or something similar)
2) Mobile and desktop support
3) Support of most browsers
4) Some animation (not required because you can get any problems with p.3) like this:
<img src="https://user-images.githubusercontent.com/73097560/115834477-dbab4500-a447-11eb-908a-139a6edaec5c.gif" width="100%"></a>

**Comment by kurnakovv** [comment]
@TanianaKur I decided do this task without frame (Updated description)

**Comment by Ulyanov-programmer** [comment]
I still don't understand why split information from one company into several cards?
In the new version of the site, you can do, for example, like this:
[(demo)](https://ulyanov-programmer.github.io/Resume/#experience)
![127 0 0 1_5500_ (1)](https://github.com/kurnakovv/Resume/assets/66691708/c3736cd5-611d-4857-b390-32f3c18a1aac)

**Comment by kurnakovv** [comment]
@Ulyanov-programmer you are absolutely right, we decided to cancel this task, but forgot do this :)
